### PR TITLE
V2Ray Support

### PR DESCRIPTION
**Pull request by reece394**
Depends on [#7](https://github.com/sn0b4ll/aria2-onion-downloader/pull/7) Being Merged

This pull request adds v2ray support as mentioned in [#6](https://github.com/sn0b4ll/aria2-onion-downloader/issues/6)

The primary benefit to this is significantly less resources being consumed whilst maintaining the same download speed as running 50 separate tor instances

Thanks to [@ValdikSS](https://github.com/ValdikSS) for the configuration files. Minor changes were made to make it work with the project

This pull request does not handle dynamically changing the number of tor circuits/instances like previously however this should be fairly simple to add.

At default it runs 50 tor circuits and this can be adjusted by changing the config.json manually for now

### CODE REVIEW

**Comment by sn0b4ll** [comment]
Hey, sorry, I only just now saw it. I will look into it in the upcoming days.

**Comment by reece394** [comment]
No problem thanks for getting back to me on it! I have hopefully fixed the merge conflicts now that #7 has now been merged

**Comment by sn0b4ll** [comment]
Love the new config. Didn't know v2ray until now, in my perspective this slacks down the complexity of the the project a lot. Again, many thanks for the addition!

**Comment by reece394** [comment]
V2ray had a bit of a learning curve when implementing it but it is nice to have everything integrated into one application.  [@ValdikSS](https://github.com/ValdikSS) sample configuration made implementing it far easier so thanks again for that! Also thanks for creating this project in the first place as it was just what I was looking for! Will make my life a lot easier going forward!

**Pull request merged**
